import "./globals.css";
import Header from "./_components/Header";
import { Amiri, Cairo, Roboto } from "next/font/google";
import FooterLayoutPart from "./_components/FooterLayoutPart";
import Footer from "./_components/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import HeaderLayoutPart from "./_components/HeaderLayoutPart";
import { CartProvider } from "./_components/CartContext";
import ViewCart from "./_components/ViewCart";

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--amiri-font",
  display: "swap",
  adjustFontFallback: false,
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--cairo-font",
  display: "swap",
  adjustFontFallback: false,
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--roboto-font",
  display: "swap",
  adjustFontFallback: false,
});
export const metadata = {
  title: "Qetmeer Farm",
  description: "Generated by create next app",
};
//TODO: manage global state

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
        className={`${cairo.variable} ${amiri.variable} ${roboto.variable} antialiased relative min-h-screen bg-background flex flex-col`}
      >
        {/* renders header conditionally based on path */}
        <HeaderLayoutPart>
          <Header />
        </HeaderLayoutPart>
        <CartProvider>
          <div className="flex-1 content-center">{children}</div>
          {/* renders footer conditionally based on path */}
          <FooterLayoutPart>
            <Footer />

            <ViewCart />
          </FooterLayoutPart>
        </CartProvider>
      </body>
    </html>
  );
}
