import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import { Amiri, Cairo, Roboto } from "next/font/google";
import Footer from "./_components/Footer";

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--amiri-font",
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--cairo-font",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--roboto-font",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
        className={`${cairo.variable} ${amiri.variable} ${roboto.variable} antialiased relative min-h-screen bg-background`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
