import "./globals.css";
import Header from "./_components/Header";
import { Amiri, Cairo, Roboto } from "next/font/google";
import Footer from "./_components/Footer";
import { ProductProvider } from "./_components/ProductContext";

const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--amiri-font",
  display: "swap",
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--cairo-font",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--roboto-font",
  display: "swap",
});

export const metadata = {
  title: "Qetmeer Farm",
  description: "Generated by create next app",
};
//TODO: manage global state

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body
        className={`${cairo.variable} ${amiri.variable} ${roboto.variable} antialiased relative min-h-screen bg-background flex flex-col`}
      >
        <Header />
        <div className="flex-1">
          <ProductProvider>{children}</ProductProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
